In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('drive/MyDrive/Datasets/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
X=df.iloc[:,3:13]
y=df.iloc[:,13]

In [4]:
#Create dummy variables
geography=pd.get_dummies(X['Geography'],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [5]:
gender

Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]

In [6]:
geography

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [7]:
# concate the DataFrames
X=pd.concat([X,geography,gender],axis=1)
X.head()

CreditScore Geography  Gender  Age  ...  EstimatedSalary  Germany  Spain  Male
0          619    France  Female   42  ...        101348.88        0      0     0
1          608     Spain  Female   41  ...        112542.58        0      1     0
2          502    France  Female   42  ...        113931.57        0      0     0
3          699    France  Female   39  ...         93826.63        0      0     0
4          850     Spain  Female   43  ...         79084.10        0      1     0

[5 rows x 13 columns]

In [8]:
## Drop Unnecessary Columns
X=X.drop(['Geography','Gender'],axis=1)

In [9]:
## Splitting the dataset into the training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [10]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [11]:
# Perform Hyperparameter Optimization
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

from keras.models import Sequential
from keras.layers import Dense,Activation,Embedding,Flatten,LeakyReLU,BatchNormalization,Dropout
from keras.activations import relu,sigmoid

def create_model(layers,activation):
  model=Sequential()
  for i,nodes in enumerate(layers):
    if i==0:
      model.add(Dense(nodes,input_dim=X_train.shape[1])) #input layer
    else:
      model.add(Dense(nodes))
    model.add(Activation(activation))
    model.add(Dropout(0.3))

  model.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid')) #Output layer

  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [12]:
model=KerasClassifier(build_fn=create_model,verbose=0)

In [13]:
layers=[(20,),(40,20),(45,30,15)] # here[40,20] means 2 hidden layers consisting of 40 and 20 neurons
activations=['sigmoid','relu']
param_grid=dict(layers=layers,activation=activations,batch_size=[128,256],epochs=[30])
param_grid

{'activation': ['sigmoid', 'relu'],
 'batch_size': [128, 256],
 'epochs': [30],
 'layers': [(20,), (40, 20), (45, 30, 15)]}

In [14]:
grid=GridSearchCV(estimator=model,param_grid=param_grid,cv=5)
grid_result=grid.fit(X_train,y_train)

In [16]:
grid_result.best_score_,grid_result.best_params_

(0.8572500109672546,
 {'activation': 'relu',
  'batch_size': 128,
  'epochs': 30,
  'layers': (45, 30, 15)})

In [18]:
pred_y=grid.predict(X_test)
y_pred=(pred_y>0.5)
y_pred

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_pred,y_test)
score=accuracy_score(y_pred,y_test)
cm,score

(array([[1518,  208],
        [  77,  197]]), 0.8575)