In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.arange(25) # no betn. 0-24

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
np.arange(0,11,2) #Start=0,end=11,step-size=2

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3) #1-dimensional vector out

array([0., 0., 0.])

In [13]:
np.zeros((5,5)) #rows=5,cols=5 in tuples

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,20) # 20 even points between 0 to 5

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

# Identity matrix

In [18]:
np.eye(4) #dimension=4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random methods of np for returning gaussian or standard normal distrubtion samples

In [19]:
np.random.rand(5) # 5 random points between 0 to 1

array([0.56324709, 0.12134103, 0.36479107, 0.01153042, 0.58690777])

In [22]:
np.random.rand(5,5) #5 random points between o-1 and 5x5 matrix

array([[0.40506391, 0.27697288, 0.09649459, 0.54963391, 0.42608999],
       [0.47866062, 0.47620024, 0.62212558, 0.8117762 , 0.14052833],
       [0.29596491, 0.84248376, 0.76467282, 0.89608475, 0.22134309],
       [0.80042237, 0.07971955, 0.00423105, 0.80041615, 0.87471263],
       [0.9118511 , 0.90681461, 0.30064435, 0.03997074, 0.31821004]])

In [24]:
np.random.randn(5) # 5 points center around 0

array([ 1.03567312,  1.2479709 , -0.22629781,  0.67298599,  0.24351893])

In [25]:
np.random.randn(5,5) # 5x5 matrix points center around 0

array([[ 0.72678066,  0.91237863,  0.02378336, -0.88668912,  1.76240941],
       [ 1.28048527, -0.63585878, -1.95067348,  0.26600065, -0.61257463],
       [-0.59502898, -0.39668473,  1.35285638,  0.1020499 ,  0.52376121],
       [-0.99930461, -1.40308751, -1.28922069, -0.48357591,  0.26448728],
       [ 0.27124814,  0.36112796,  0.36368572,  1.61551198, -0.75149171]])

In [26]:
np.random.randint(1,100) # random no between 1-99

37

In [30]:
rarr=np.random.randint(1,100,10) # 10 randint betn. 1-99

In [31]:
rarr

array([ 8, 14, 46, 39, 56, 51, 59, 86, 97, 74])

In [33]:
rarr.reshape(2,5) #Rows x Cols must be equal to array size

array([[ 8, 14, 46, 39, 56],
       [51, 59, 86, 97, 74]])

In [34]:
rarr.max()

97

In [35]:
rarr.min()

8

In [36]:
rarr.argmax() #index of max val

8

In [37]:
rarr.argmin() #index of min val

0

In [43]:
rarr.shape #1 dimensional vector

(10,)

In [41]:
nvec=rarr.reshape(5,2)

In [42]:
nvec.shape #2 dimensional vector

(5, 2)

In [45]:
nvec.dtype #data type of the array

dtype('int32')