From `Scratch`

In [2]:
import numpy as np

In [3]:
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1.0],
        [.5,-.91,.26,-.5],
        [-.26,-.27,.17,.87]]
biases=[2,3,0.5]

In [4]:
layer_output=[]
for neuron_weights,neuron_bias in zip(weights,biases):
    neuron_output=0
    for n_input,weight in zip(inputs,neuron_weights):
        neuron_output+=n_input*weight
    neuron_output+=neuron_bias
    layer_output.append(neuron_output)
print(f"Layer output:{layer_output}")

Layer output:[4.8, 1.21, 2.385]


### Using `dot` product for-

* Single sample of input features (Vector)

[1 , 2].[3 , 2]=[1x3 , 2x2]

In [5]:
sum_of_weights_dot_inputs=np.dot(weights,inputs)
sum_of_weights_dot_inputs

array([ 2.8  , -1.79 ,  1.885])

In [6]:
biases

[2, 3, 0.5]

In [7]:
layer_output=sum_of_weights_dot_inputs+biases
layer_output

array([4.8  , 1.21 , 2.385])

### Using `dot` product for-

* Batch of samples (Matrix)

In [8]:
inputs=[[1,2,3,2.5],
       [2,5,-1,2],
       [-1.5,2.7,3.3,-.8]]

weights=[[0.2,0.8,-0.5,1.0],
        [.5,-.91,.26,-.5],
        [-.26,-.27,.17,.87]]

biases=[2,3,0.5]

dot_product=np.dot(inputs,np.array(weights).T) #inputs(3,4)*weights(3,4).T
dot_product

array([[ 2.8  , -1.79 ,  1.885],
       [ 6.9  , -4.81 , -0.3  ],
       [-0.59 , -1.949, -0.474]])

In [9]:
layer_output=dot_product+biases
layer_output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

### Layers and objects

In [10]:
np.random.seed(0)
X=[[1,2,3,2.5],
   [2,5,-1,2],
   [-1.5,2.7,3.3,-.8]]

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.1*np.random.randn(n_inputs,n_neurons) # n_inputs x n_neurons matrix points center around 0
        self.biases=np.zeros((1,n_neurons)) #rows=1,cols=n_neurons in tuples
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases

In [11]:
layer1=Layer_Dense(4,5)
layer1.forward(X)
print(f"Layer1:\n{layer1.output}")

layer2=Layer_Dense(5,2)
layer2.forward(layer1.output)
print(f"\nLayer2:\n{layer2.output}")

Layer1:
[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]

Layer2:
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


### Hidden Layer Activation

In [13]:
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

X,y=spiral_data(100,3)

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.1*np.random.randn(n_inputs,n_neurons) # n_inputs x n_neurons matrix points center around 0
        self.biases=np.zeros((1,n_neurons)) #rows=1,cols=n_neurons in tuples
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases
        
class Activation_ReLU:
    def forward(self,inputs):
        self.output=np.maximum(0,inputs) # negative i/p becomes 0 & to get non-zero as o/p we need to make biases non-zero

layer1=Layer_Dense(2,5)
layer1.forward(X)
print(f"Layer1:\n{layer1.output}")

activation1=Activation_ReLU()
activation1.forward(layer1.output)
print(f"\nHidden layer activation:\n{activation1.output}")

Layer1:
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]

Hidden layer activation:
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+0